root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "test", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  log = ""
  rerun = false
  stop_on_error = true

[color]
  build = ""
  main = ""
  runner = ""
  watcher = ""

[log]
  silent = true
  main_only = true
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false